version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: thainan-langflow_web_1
      APP_PORT: 7860
      PROXY_AUTH_ADD: "false"
  web:
    image: langflowai/langflow:latest
    restart: on-failure
    environment:
      LANGFLOW_HOST: "0.0.0.0"
      LANGFLOW_PORT: "7860"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/langflow
