version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: thainan-spliit_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
  web:
    image: ghcr.io/spliit-app/spliit:latest
    user: "1000:1000"
    restart: on-failure
    depends_on:
      - db
    environment:
      POSTGRES_PRISMA_URL: postgresql://spliit:spliit@thainan-spliit_db_1:5432/spliit
      POSTGRES_URL_NON_POOLING: postgresql://spliit:spliit@thainan-spliit_db_1:5432/spliit
    volumes:
      - ${APP_DATA_DIR}/data/cache:/usr/app/.next/cache
  db:
    image: postgres:17-alpine
    user: "1000:1000"
    restart: on-failure
    environment:
      POSTGRES_USER: spliit
      POSTGRES_PASSWORD: spliit
      POSTGRES_DB: spliit
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
