version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: thainan-redlib_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  web:
    image: quay.io/redlib/redlib:latest
    user: "65534:65534"
    read_only: true
    restart: on-failure
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
