# Umbrel sources this before compose up
export FLUXER_DOMAIN="${DEVICE_DOMAIN_NAME}"
export FLUXER_PUBLIC_SCHEME="http"
export FLUXER_PUBLIC_PORT="3005"
export FLUXER_PUBLIC_ORIGIN="http://${DEVICE_DOMAIN_NAME}:3005"
export FLUXER_EDGE_SITE_ADDRESS=":8080"
export FLUXER_PASSKEY_RP_ID="${DEVICE_DOMAIN_NAME}"
